# Generated by Django 5.1.1 on 2024-12-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='姓')),
                ('name', models.CharField(max_length=30, verbose_name='名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('date', models.DateField(verbose_name='日付')),
                ('time', models.TimeField(verbose_name='時刻')),
                ('status', models.CharField(max_length=10, verbose_name='ステータス')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='メッセージ')),
            ],
        ),
    ]
