# Generated by Django 5.1.1 on 2025-01-16 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='STORE_ID')),
                ('name', models.CharField(max_length=100, verbose_name='店名')),
                ('owner', models.CharField(blank=True, max_length=15, null=True, verbose_name='店長')),
                ('address', models.TextField(verbose_name='住所')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='USER_ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('user_name', models.CharField(max_length=50, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='picture/user_avatar', verbose_name='アバター')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='APPOINTMENT_ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='picture/user_appointment', verbose_name='写真')),
                ('date', models.DateField(verbose_name='日付')),
                ('time', models.TimeField(verbose_name='時刻')),
                ('message', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.store', verbose_name='店名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.user', verbose_name='ユーザー')),
            ],
        ),
    ]
