# Generated by Django 5.1.1 on 2024-12-05 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='myapp/picture'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='変更時間'),
            preserve_default=False,
        ),
    ]
