# Generated by Django 5.1.1 on 2024-12-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='名前')),
                ('first_name', models.CharField(max_length=30, verbose_name='姓')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=30, verbose_name='パスワード')),
            ],
        ),
    ]
